### ISSUE TITLE
How to get sentence vectors?

### ISSUE THREAD

**Issue by jd4ds** [EmilHvitfeldt/fastTextR#4]
Hello everyone,

I have trained my own fastText model with this package (through `{wordsalad}`) and would now like to obtain "sentence vectors" based on my model for new observations. This package does not implement such a functionality as far as I can see. However, fastText seems to have implemented a function for this: https://github.com/facebookresearch/fastText/blob/a20c0d27cd0ee88a25ea0433b7f03038cd728459/src/fasttext.cc#L490

As far as I can make out, the function to get sentence vectors seems to perform roughly the following steps:
- It calculates the norm of each word vector in a sentence, using the function `norm`.
- It divides each word vector by its norm to normalise it.
- It adds a special end-of-sentence token `</s>`.
- It calculates the average of all normalised word vectors and the end-of-sentence token.

In addition, `{textrecipes}` also seems to provide internal functionality to get a common vector for the aggregate of multiple tokens.

What would be the best way for me to get a "sentence vector". Should this function be exported from the original C++ package here in this package? Do I need to use `{textrecipes}` to get this functionality or should I/must I write my own function?

Many thanks and best regards!

**Comment by EmilHvitfeldt** [comment]
Hello @jd4ds 👋 

This is a good question, I think what you are asking for is something that should be provided here in this package.

I think ideally this should be by exporting that function from C++ to the user.

Unfortunately, I don't have much bandwidth to work on this package at the moment

**Comment by jd4ds** [comment]
Hi @EmilHvitfeldt ,
I'm not sure if I'll get round to it and if I would be able to, but if so, would you consider reviewing a PR of mine with this functionality exported from C++ and doing a CRAN release?
Thanks and best regards!

**Comment by EmilHvitfeldt** [comment]
PRs are always welcome!

**Comment by jd4ds** [comment]
Closed by #5
